[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main.py"

[[services]]
name = "bot"
type = "worker"
startCommand = "python main.py"

[[services]]
name = "api"
type = "web"
startCommand = "uvicorn api_server:app --host 0.0.0.0 --port 8000"
